service:
  profile-properties:
    profile-edit-cooldown: ${PROFILE_CHANGES_COOLDOWN}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

server:
  port: ${APPLICATION_PORT}

spring:
  kafka:
    bootstrap-servers: event-router-kafka:29092
    consumer:
      group-id: mg-profile-service-kafka-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 15000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 2147483647
        retry.backoff.ms: 10000

  application:
    name: ${APPLICATION_PROJECT_NAME}

  main:
    banner-mode: off

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: mg-profile-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mg-gateway-server-service:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /profile/public/v3/api-docs
  swagger-ui:
    enabled: false